- name: Setup EC2 instance
  hosts: webservers
  become: true
  vars_files:
    - vault.yml 
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: latest

    - name: Ensure Docker is enabled and started
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reboot the server to apply group changes
      reboot:
        msg: "Reboot initiated by Ansible after adding user to docker group"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30

    - name: Check Docker status with docker info
      command: docker info
      register: docker_info_output
      changed_when: false
      failed_when: docker_info_output.rc != 0

    - name: Copy docker-compose.yml with permissions
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        mode: '0644'
    
    - name: Copy .env with permissions
      copy:
        src: .env
        dest: /home/ubuntu/.env
        mode: '0644'
      
    - name: Install GitHub Runner dependencies
      apt:
        name: curl
        state: present
    - name: Download and configure GitHub Runner
      become_user: ubuntu
      shell: |
        mkdir -p /home/ubuntu/actions-runner && cd /home/ubuntu/actions-runner
        curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
        tar xzf actions-runner-linux-x64-2.317.0.tar.gz
        ./config.sh --url https://github.com/Usf277/Todo-List-nodejs --token {{ GITHUB_TOKEN }} --unattended
        ./svc.sh install && ./svc.sh start
      args:
        creates: /home/ubuntu/actions-runner/run.sh