name: Deploy to EC2

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64] 
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and redeploy Docker image
        run: |
          cd /home/ubuntu/
          docker-compose down
          docker-compose pull
          docker-compose up -d 
